package com.personal.kakeibox.ui.theme

import com.personal.kakeibox.data.preferences.AppLanguage

data class AppStrings(
    val salary: String,
    val exercise: String,
    val kotoba: String,
    val settings: String,
    val visuals: String,
    val themesAndStyles: String,
    val preferences: String,
    val currencyAndMode: String,
    val security: String,
    val biometricsAndLock: String,
    val about: String,
    val version: String,
    val searchSettings: String,
    val regionalLocaleOptions: String,
    val appLanguage: String,
    val selectLanguageDesc: String,
    val currencySymbol: String,
    val defineCurrencyDesc: String,
    val appCustomization: String,
    val reorderNavTabs: String,
    val manageNavTabsDesc: String,
    val themeColorSettings: String,
    val themeFlavorTitle: String,
    val themeFlavorDesc: String,
    val darkThemeTitle: String,
    val darkThemeDesc: String,
    val totalSavings: String,
    val totalRemittance: String,
    val totalEarnings: String,
    val payPeriod: String,
    val allocations: String,
    val addSalary: String,
    val editSalary: String,
    val newWorkout: String,
    val editWorkout: String,
    val workoutName: String,
    val sets: String,
    val reps: String,
    val instructions: String,
    val scheduleDay: String,
    val save: String,
    val cancel: String,
    
    // Salary Screen
    val totalCumulativeEarnings: String,
    val thisMonth: String,
    val nextPayday: String,
    val daysLeft: String,
    val incomeVsSavingsTrend: String,
    val income: String,
    val salaryAllocationPlayground: String,
    val allocationDesc: String,
    val projectedAnnualSavings: String,
    val estDisposableIncome: String,
    val history: String,
    val seeAll: String,
    val allTime: String,
    val thisYear: String,
    val highSavings: String,
    
    // Exercise Screen
    val scheduleWorkouts: String,
    val workouts: String,
    val setsDone: String,
    val active: String,
    val noWorkoutsLogged: String,
    
    // Settings Screen
    val dynamicColorSaturation: String,
    val fineTuneWallpaper: String,
    val dynamicColorTint: String,
    val extractAccentWallpaper: String,
    val themeControlsIntensity: String,
    val controlToneSaturation: String,
    val typographyLayoutSettings: String,
    val appFontFamily: String,
    val chooseGlobalTypeface: String,
    val backgroundStyle: String,
    val chooseBackgroundStyle: String,
    val navbarAnimation: String,
    val selectNavbarAnimation: String,
    val privacyAppLock: String,
    val privacyModeProtection: String,
    val maskSensitiveTotals: String,
    val biometricLockGuard: String,
    val protectAccountBiometrics: String,
    val dataManagement: String,
    val backupDatabase: String,
    val exportLocalDbCopy: String,
    val restoreDatabase: String,
    val importBackupDbFile: String,
    val exportFinancialHistory: String,
    val downloadCsvHistory: String,
    // About section
    val informationTitle: String,
    val aboutVersion: String,
    val aboutVersionDesc: String,
    val aboutDeveloper: String,
    val aboutDeveloperDesc: String,
    val aboutGithub: String,
    val aboutGithubDesc: String,
    // Exercise sheet
    val defineWorkoutDesc: String,
    val dayMonday: String,
    val dayTuesday: String,
    val dayWednesday: String,
    val dayThursday: String,
    val dayFriday: String,
    val daySaturday: String,
    val daySunday: String,
    
    // New localization fields
    val heroCommandGauge: String,
    val recentActivity: String,
    val quickActions: String,
    val financialOverview: String,
    val personalBests: String,
    val kineticNexus: String,
    val dismissPortal: String,
    val privacyOn: String,
    val privacyOff: String,
    val searchVocabulary: String,
    val markAsKnown: String,
    val reviewLater: String,
    val flipCard: String,
    val studySession: String,
    val noCardsFound: String,
    val financialMatrix: String,
    val savingsNexus: String,
    val monthlyBreakdown: String,
    val addRecord: String,
    val exerciseForge: String,
    val maxWeight: String,
    val restDayActive: String,
    val continuousPrimaryHue: String,
    val launchSetupWizard: String,
    val reRunOnboardingFlow: String,
    val home: String,
    
    // Screenshot audit fields
    val liveGauge: String,
    val daysTillPayday: String,
    val remainingCommandBalance: String,
    val paydayCountdownTimeline: String,
    val elapsed: String,
    val logAction: String,
    val workout: String,
    val daysCount: String,
    val commandLaunchpad: String,
    val dailySnapshotActivity: String,
    val onTrack: String,
    val dueNow: String,
    val monthlyBudget: String,
    val saved: String,
    val vocabReview: String,
    val words: String,
    val portalHeader: String,
    val cmdDashboardSub: String,
    val homeOverviewSub: String,
    val finNexusSub: String,
    val salSavingsSub: String,
    val athForgeSub: String,
    val workGymSub: String,
    val vocabDeckSub: String,
    val japKotobaSub: String,
    val aesCustomSub: String,
    val themeStudioSub: String,
    val vittaFooter: String,
    val editionBadge: String,
    
    // Salary Tab Audit Fields
    val currentlyTracking: String,
    val lifetime: String,
    val daysTillNextPayday: String,
    val heroSalarySubText: String,
    val continuityIsPower: String,
    val scrollToSeeMore: String,
    val rightWithHearts: String,
    val balancedSplit: String,
    val monthJan: String,
    val monthFeb: String,
    val monthMar: String,
    val monthApr: String,
    val monthMay: String,
    val monthJun: String,
    val monthJul: String,
    val monthAug: String,
    val monthSep: String,
    val monthOct: String,
    val monthNov: String,
    val monthDec: String,

    // Salary History Card & Birthday Sheet Fields
    val spent: String,
    val note: String,
    val editRecord: String,
    val netRemaining: String,
    val salaryAmountLabel: String,
    val savingsLabel: String,
    val remittanceLabel: String,
    val noteLabel: String,
    val saveRecord: String,
    val updateRecord: String,
    val salaryHistory: String,
    val birthdaysHub: String,
    val neverMissCelebration: String,
    val noBirthdaysSaved: String,
    val tapPlusToAdd: String,
    val addNewBirthday: String,
    val neverMissCelebrationDetail: String,
    val whosBirthdayIsIt: String,
    val personsName: String,
    val birthdayDate: String,
    val saveBirthday: String,
    val done: String,
    val shlok: String,
    val medicationTracker: String,
    val prescriptionLog: String,
    val breakfastDose: String,
    val lunchDose: String,
    val dinnerDose: String,
    val editReminderTimes: String,
    val saveTimes: String,
    val situationalShloks: String,
    val marathiMeaningLabel: String
)

val EnglishStrings = AppStrings(
    salary = "Salary",
    exercise = "Exercise",
    kotoba = "Kotoba",
    settings = "Settings",
    visuals = "Visuals",
    themesAndStyles = "Themes & Styles",
    preferences = "Preferences",
    currencyAndMode = "Currency & Mode",
    security = "Security",
    biometricsAndLock = "Biometrics & Lock",
    about = "About",
    version = "KakeiboX v1.0",
    searchSettings = "Search settings...",
    regionalLocaleOptions = "Regional & Locale Options",
    appLanguage = "App Language",
    selectLanguageDesc = "Select localized app string translation language.",
    currencySymbol = "Currency Symbol",
    defineCurrencyDesc = "Define standard monetary symbol applied to entries.",
    appCustomization = "App Customization",
    reorderNavTabs = "Reorder Navigation Tabs",
    manageNavTabsDesc = "Manage and drag routes inside bottom layout navbar.",
    themeColorSettings = "Theme & Color Settings",
    themeFlavorTitle = "Theme Aesthetic Flavor",
    themeFlavorDesc = "Choose curated M3 Expressive design color palette.",
    darkThemeTitle = "App Dark Theme",
    darkThemeDesc = "Light, dark, or system-adaptive dark mode preference.",
    totalSavings = "Total Savings",
    totalRemittance = "Total Remittance",
    totalEarnings = "TOTAL EARNINGS",
    payPeriod = "PAY PERIOD",
    allocations = "ALLOCATIONS",
    addSalary = "Add Salary",
    editSalary = "Edit Salary",
    newWorkout = "New Workout",
    editWorkout = "Edit Workout",
    workoutName = "Workout Name",
    sets = "SETS",
    reps = "REPS",
    instructions = "Instructions / Notes",
    scheduleDay = "SCHEDULE DAY",
    save = "Save",
    cancel = "Cancel",
    
    // Salary Screen
    totalCumulativeEarnings = "TOTAL CUMULATIVE EARNINGS",
    thisMonth = "THIS MONTH",
    nextPayday = "NEXT PAYDAY",
    daysLeft = "Days Left",
    incomeVsSavingsTrend = "INCOME VS. SAVINGS TREND",
    income = "Income",
    salaryAllocationPlayground = "SALARY ALLOCATION PLAYGROUND",
    allocationDesc = "Adjust the slider to simulate target savings rates and project wealth trajectory.",
    projectedAnnualSavings = "PROJECTED ANNUAL SAVINGS",
    estDisposableIncome = "EST. DISPOSABLE INCOME",
    history = "History",
    seeAll = "See All",
    allTime = "All Time",
    thisYear = "This Year",
    highSavings = "High Savings",
    
    // Exercise Screen
    scheduleWorkouts = "SCHEDULE WORKOUTS",
    workouts = "Workouts",
    setsDone = "Sets Done",
    active = "Active",
    noWorkoutsLogged = "No workouts logged for",
    
    // Settings Screen
    dynamicColorSaturation = "Dynamic Color Saturation",
    fineTuneWallpaper = "Fine-tune wallpaper extraction intensity.",
    dynamicColorTint = "Dynamic Color Tint",
    extractAccentWallpaper = "Extract accent colors from device wallpaper (M3 mode only).",
    themeControlsIntensity = "Theme Controls Intensity",
    controlToneSaturation = "Control tone saturation and contrast (Neutral, Soft, Bright, Bold).",
    typographyLayoutSettings = "Typography & Layout Settings",
    appFontFamily = "App Font Family",
    chooseGlobalTypeface = "Choose global typeface applied to all text components.",
    backgroundStyle = "Background Style",
    chooseBackgroundStyle = "Choose background style for screen canvas backdrop.",
    navbarAnimation = "Navbar Animation",
    selectNavbarAnimation = "Select animation style for the floating navigation bar.",
    privacyAppLock = "Privacy & App Lock",
    privacyModeProtection = "Privacy Mode Protection",
    maskSensitiveTotals = "Mask sensitive financial totals with dots on dashboard.",
    biometricLockGuard = "Biometric Lock Guard",
    protectAccountBiometrics = "Protect account information with fingerprint lock.",
    dataManagement = "Data Management",
    backupDatabase = "Backup Database",
    exportLocalDbCopy = "Export a copy of your local database (.db) file to device storage.",
    restoreDatabase = "Restore Database",
    importBackupDbFile = "Import a previously backed up (.db) file to restore your data.",
    exportFinancialHistory = "Export Financial History",
    downloadCsvHistory = "Download history records, wage totals, and travels as CSV file.",
    // About section
    informationTitle = "Information",
    aboutVersion = "Version",
    aboutVersionDesc = "v1.0.0 Stable",
    aboutDeveloper = "Developer",
    aboutDeveloperDesc = "Lalit",
    aboutGithub = "GitHub",
    aboutGithubDesc = "Source Code",
    // Exercise sheet
    defineWorkoutDesc = "Define workout target & parameters",
    dayMonday = "Monday",
    dayTuesday = "Tuesday",
    dayWednesday = "Wednesday",
    dayThursday = "Thursday",
    dayFriday = "Friday",
    daySaturday = "Saturday",
    daySunday = "Sunday",
    
    // New localization values
    heroCommandGauge = "HERO COMMAND GAUGE",
    recentActivity = "RECENT ACTIVITY",
    quickActions = "QUICK ACTIONS",
    financialOverview = "FINANCIAL OVERVIEW",
    personalBests = "PERSONAL BESTS",
    kineticNexus = "KINETIC NEXUS",
    dismissPortal = "DISMISS PORTAL",
    privacyOn = "PRIVACY: ON",
    privacyOff = "PRIVACY: OFF",
    searchVocabulary = "Search vocabulary...",
    markAsKnown = "MARK AS KNOWN",
    reviewLater = "REVIEW LATER",
    flipCard = "FLIP CARD",
    studySession = "STUDY SESSION",
    noCardsFound = "No cards found",
    financialMatrix = "FINANCIAL MATRIX",
    savingsNexus = "SAVINGS NEXUS",
    monthlyBreakdown = "MONTHLY BREAKDOWN",
    addRecord = "ADD RECORD",
    exerciseForge = "EXERCISE FORGE",
    maxWeight = "MAX WEIGHT",
    restDayActive = "REST DAY ACTIVE",
    continuousPrimaryHue = "Continuous Primary Hue",
    launchSetupWizard = "Launch Setup Wizard 🪄",
    reRunOnboardingFlow = "Re-run the M3 Expressive onboarding flow",
    home = "HOME",
    
    // Screenshot audit values
    liveGauge = "LIVE GAUGE",
    daysTillPayday = "DAYS TILL PAYDAY",
    remainingCommandBalance = "REMAINING COMMAND BALANCE",
    paydayCountdownTimeline = "PAYDAY COUNTDOWN TIMELINE",
    elapsed = "ELAPSED",
    logAction = "LOG →",
    workout = "WORKOUT",
    daysCount = "DAYS",
    commandLaunchpad = "COMMAND LAUNCHPAD",
    dailySnapshotActivity = "DAILY SNAPSHOT & ACTIVITY",
    onTrack = "ON TRACK",
    dueNow = "DUE NOW",
    monthlyBudget = "MONTHLY BUDGET",
    saved = "SAVED",
    vocabReview = "VOCAB REVIEW",
    words = "WORDS",
    portalHeader = "00 / PORTAL",
    cmdDashboardSub = "01 • COMMAND DASHBOARD",
    homeOverviewSub = "HOME & OVERVIEW",
    finNexusSub = "02 • FINANCIAL NEXUS",
    salSavingsSub = "SALARY & SAVINGS",
    athForgeSub = "03 • ATHLETIC FORGE",
    workGymSub = "WORKOUT & GYM",
    vocabDeckSub = "04 • VOCABULARY DECK",
    japKotobaSub = "JAPANESE KOTOBA",
    aesCustomSub = "05 • AESTHETIC CUSTOMIZER",
    themeStudioSub = "THEME STUDIO",
    vittaFooter = "VITTA 2026 • M3 EXPRESSIVE",
    editionBadge = "EDITION",
    
    // Salary Tab Audit Values
    currentlyTracking = "Currently tracking...",
    lifetime = "LIFETIME",
    daysTillNextPayday = "DAYS TILL THE NEXT PAYDAY",
    heroSalarySubText = "BUT BEFORE THE LAUNCH OF THIS MONTH'S SALARY, LET'S TAKE GOOD CARE OF YOUR SOON-TO-BE 'OLD' SAVINGS,",
    continuityIsPower = "Continuity is Power",
    scrollToSeeMore = "Scroll to see more...",
    rightWithHearts = "RIGHT?! ♡♡",
    balancedSplit = "Simulation: Balanced split 👍",
    monthJan = "Jan",
    monthFeb = "Feb",
    monthMar = "Mar",
    monthApr = "Apr",
    monthMay = "May",
    monthJun = "Jun",
    monthJul = "Jul",
    monthAug = "Aug",
    monthSep = "Sep",
    monthOct = "Oct",
    monthNov = "Nov",
    monthDec = "Dec",

    // Salary History Card & Birthday Sheet Fields
    spent = "SPENT",
    note = "NOTE",
    editRecord = "Edit Record",
    netRemaining = "Net Remaining",
    salaryAmountLabel = "Salary Amount",
    savingsLabel = "Savings",
    remittanceLabel = "Remittance",
    noteLabel = "Note / Description",
    saveRecord = "Save Record",
    updateRecord = "Update Record",
    salaryHistory = "Salary History",
    birthdaysHub = "Birthdays Hub",
    neverMissCelebration = "Never miss a celebration",
    noBirthdaysSaved = "No birthdays saved",
    tapPlusToAdd = "Tap the '+' to start adding",
    addNewBirthday = "Add New Birthday",
    neverMissCelebrationDetail = "Make sure you never miss a celebration!",
    whosBirthdayIsIt = "Who's birthday is it?",
    personsName = "Person's Name",
    birthdayDate = "Birthday Date",
    saveBirthday = "Save Birthday",
    done = "Done",
    shlok = "Shlok",
    medicationTracker = "Medication Tracker",
    prescriptionLog = "60-Day Prescription Log",
    breakfastDose = "Breakfast (Office)",
    lunchDose = "Lunch (Office)",
    dinnerDose = "Dinner (Home)",
    editReminderTimes = "Edit Reminder Times",
    saveTimes = "Save Times",
    situationalShloks = "Situational Shloks",
    marathiMeaningLabel = "Marathi Meaning (मराठी भावार्थ)"
)

val JapaneseStrings = AppStrings(
    salary = "給与",
    exercise = "運動",
    kotoba = "言葉",
    settings = "設定",
    visuals = "ビジュアル",
    themesAndStyles = "テーマ＆スタイル",
    preferences = "環境設定",
    currencyAndMode = "通貨＆モード",
    security = "セキュリティ",
    biometricsAndLock = "生体認証＆ロック",
    about = "アプリ情報",
    version = "KakeiboX v1.0",
    searchSettings = "設定を検索...",
    regionalLocaleOptions = "地域・言語設定",
    appLanguage = "アプリ言語",
    selectLanguageDesc = "表示言語を選択します。",
    currencySymbol = "通貨記号",
    defineCurrencyDesc = "標準で使用する通貨記号を設定します。",
    appCustomization = "アプリのカスタマイズ",
    reorderNavTabs = "ナビゲーション順序",
    manageNavTabsDesc = "ボトムバーのタブ順序を変更します。",
    themeColorSettings = "テーマ＆カラー設定",
    themeFlavorTitle = "デザインテーマ",
    themeFlavorDesc = "お好みのカラーパレットを選択します。",
    darkThemeTitle = "ダークモード設定",
    darkThemeDesc = "ライト、ダーク、システム連動の切り替え。",
    totalSavings = "総貯蓄額",
    totalRemittance = "総送金額",
    totalEarnings = "総収入",
    payPeriod = "給与期間",
    allocations = "配分設定",
    addSalary = "給与を追加",
    editSalary = "給与を編集",
    newWorkout = "新規ワークアウト",
    editWorkout = "ワークアウト編集",
    workoutName = "種目名",
    sets = "セット数",
    reps = "回数",
    instructions = "メモ・説明",
    scheduleDay = "実施曜日",
    save = "保存",
    cancel = "キャンセル",
    
    // Salary Screen
    totalCumulativeEarnings = "累計総収入",
    thisMonth = "今月の給与",
    nextPayday = "次回の給料日",
    daysLeft = "日残り",
    incomeVsSavingsTrend = "収入・貯蓄推移",
    income = "収入",
    salaryAllocationPlayground = "給与配分シミュレーション",
    allocationDesc = "スライダーを調整して目標貯蓄率と資産の推移をシミュレーションします。",
    projectedAnnualSavings = "年間予想貯蓄額",
    estDisposableIncome = "推定可処分所得",
    history = "履歴",
    seeAll = "すべて表示",
    allTime = "全期間",
    thisYear = "今年",
    highSavings = "高貯蓄",
    
    // Exercise Screen
    scheduleWorkouts = "ワークアウト予定",
    workouts = "ワークアウト",
    setsDone = "セット完了",
    active = "有効",
    noWorkoutsLogged = "ワークアウトが登録されていません:",
    
    // Settings Screen
    dynamicColorSaturation = "ダイナミックカラー彩度",
    fineTuneWallpaper = "壁紙カラー抽出の強度を微調整します。",
    dynamicColorTint = "ダイナミックカラーティント",
    extractAccentWallpaper = "壁紙からアクセントカラーを抽出します。",
    themeControlsIntensity = "テーマコントラスト強度",
    controlToneSaturation = "トーンの彩度とコントラストを調整します。",
    typographyLayoutSettings = "フォント＆レイアウト設定",
    appFontFamily = "アプリフォント",
    chooseGlobalTypeface = "すべてのテキストに使用するフォントを選択します。",
    backgroundStyle = "背景スタイル",
    chooseBackgroundStyle = "画面背景のスタイルを選択します。",
    navbarAnimation = "ナビバーアニメーション",
    selectNavbarAnimation = "ナビゲーションバーのアニメーションを選択します。",
    privacyAppLock = "プライバシー＆アプリロック",
    privacyModeProtection = "プライバシーモード保護",
    maskSensitiveTotals = "ダッシュボードの金額をドットで非表示にします。",
    biometricLockGuard = "生体認証ロック",
    protectAccountBiometrics = "指紋認証でアカウント情報を保護します。",
    dataManagement = "データ管理",
    backupDatabase = "データベースバックアップ",
    exportLocalDbCopy = "ローカルデータベースのバックアップを出力します。",
    restoreDatabase = "データベース復元",
    importBackupDbFile = "バックアップファイルからデータを復元します。",
    exportFinancialHistory = "履歴データCSV出力",
    downloadCsvHistory = "給与・支出履歴をCSVファイルとして保存します。",
    // About section
    informationTitle = "アプリ情報",
    aboutVersion = "バージョン",
    aboutVersionDesc = "v1.0.0 安定版",
    aboutDeveloper = "開発者",
    aboutDeveloperDesc = "Lalit",
    aboutGithub = "GitHub",
    aboutGithubDesc = "ソースコード",
    // Exercise sheet
    defineWorkoutDesc = "ワークアウト目標を設定します",
    dayMonday = "月曜日",
    dayTuesday = "火曜日",
    dayWednesday = "水曜日",
    dayThursday = "木曜日",
    dayFriday = "金曜日",
    daySaturday = "土曜日",
    daySunday = "日曜日",
    
    // New localization values
    heroCommandGauge = "ヒーロー・コマンドゲージ",
    recentActivity = "最近のアクティビティ",
    quickActions = "クイック操作",
    financialOverview = "財務概要",
    personalBests = "自己ベスト",
    kineticNexus = "キネティック・ネクサス",
    dismissPortal = "ポータルを閉じる",
    privacyOn = "プライバシー: ON",
    privacyOff = "プライバシー: OFF",
    searchVocabulary = "単語を検索...",
    markAsKnown = "習得済みにする",
    reviewLater = "後で復習",
    flipCard = "カードを裏返す",
    studySession = "学習セッション",
    noCardsFound = "単語カードが見つかりません",
    financialMatrix = "財務マトリクス",
    savingsNexus = "貯蓄ネクサス",
    monthlyBreakdown = "月次内訳",
    addRecord = "記録を追加",
    exerciseForge = "トレーニング・フォージ",
    maxWeight = "最大重量",
    restDayActive = "本日お休み",
    continuousPrimaryHue = "連続プライマリ色相",
    launchSetupWizard = "セットアップ・ウィザード起動 🪄",
    reRunOnboardingFlow = "M3 Expressiveオンボーディングを再開します",
    home = "ホーム",

    // Screenshot audit Japanese values
    liveGauge = "ライブメーター",
    daysTillPayday = "給料日まで",
    remainingCommandBalance = "残高概要",
    paydayCountdownTimeline = "給料日カウントダウン",
    elapsed = "経過",
    logAction = "記録 →",
    workout = "ワークアウト",
    daysCount = "日間",
    commandLaunchpad = "コマンド・ローンチパッド",
    dailySnapshotActivity = "日次アクティビティ",
    onTrack = "順調",
    dueNow = "要復習",
    monthlyBudget = "今月の予算",
    saved = "貯蓄済み",
    vocabReview = "単語復習",
    words = "単語",
    portalHeader = "00 / ポータル",
    cmdDashboardSub = "01 • コマンド・ダッシュボード",
    homeOverviewSub = "ホーム＆概要",
    finNexusSub = "02 • 財務ネクサス",
    salSavingsSub = "給与＆貯蓄",
    athForgeSub = "03 • アスレチック・フォージ",
    workGymSub = "ワークアウト＆ジム",
    vocabDeckSub = "04 • 語彙デッキ",
    japKotobaSub = "日本語コトバ",
    aesCustomSub = "05 • アステティック・カスタム",
    themeStudioSub = "テーマ・スタジオ",
    vittaFooter = "VITTA 2026 • M3 エクスプレッシブ",
    editionBadge = "エディション",

    // Salary Tab Audit Values
    currentlyTracking = "追跡中...",
    lifetime = "全期間",
    daysTillNextPayday = "次回の給料日まであと",
    heroSalarySubText = "今月の給与支給前に、これまでの貯蓄を大切に管理しましょう。",
    continuityIsPower = "継続は力なり",
    scrollToSeeMore = "スクロールして詳細を表示...",
    rightWithHearts = "ね？！ ♡♡",
    balancedSplit = "シミュレーション: バランス配分 👍",
    monthJan = "1月",
    monthFeb = "2月",
    monthMar = "3月",
    monthApr = "4月",
    monthMay = "5月",
    monthJun = "6月",
    monthJul = "7月",
    monthAug = "8月",
    monthSep = "9月",
    monthOct = "10月",
    monthNov = "11月",
    monthDec = "12月",

    // Salary History Card & Birthday Sheet Fields
    spent = "支出",
    note = "メモ",
    editRecord = "記録を編集",
    netRemaining = "差引残額",
    salaryAmountLabel = "給料額",
    savingsLabel = "貯蓄額",
    remittanceLabel = "仕送り・送金額",
    noteLabel = "メモ・説明",
    saveRecord = "記録を保存",
    updateRecord = "記録を更新",
    salaryHistory = "給与履歴",
    birthdaysHub = "誕生日ハブ",
    neverMissCelebration = "大切なお祝いを見逃さない",
    noBirthdaysSaved = "誕生日が登録されていません",
    tapPlusToAdd = "「+」をタップして追加",
    addNewBirthday = "新しい誕生日を追加",
    neverMissCelebrationDetail = "大切な人の記念日を記録しましょう！",
    whosBirthdayIsIt = "どなたの誕生日ですか？",
    personsName = "お名前",
    birthdayDate = "生年月日",
    saveBirthday = "誕生日を保存",
    done = "完了",
    shlok = "シュローカ",
    medicationTracker = "服薬トラッカー",
    prescriptionLog = "60日間 処方箋記録",
    breakfastDose = "朝食後 (オフィス)",
    lunchDose = "昼食後 (オフィス)",
    dinnerDose = "夕食後 (自宅)",
    editReminderTimes = "リマインダー時間を編集",
    saveTimes = "時間を保存",
    situationalShloks = "シチュエーション別シュローカ",
    marathiMeaningLabel = "マラーティー語の意味 (मराठी भावार्थ)"
)

fun getAppStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.JAPANESE -> JapaneseStrings
    }
}
