package com.personal.kakeibox.ui.theme

import com.personal.kakeibox.data.preferences.AppLanguage

data class AppStrings(
    val salary: String,
    val exercise: String,
    val settings: String,
    val visuals: String,
    val themesAndStyles: String,
    val preferences: String,
    val currencyAndMode: String,
    val security: String,
    val biometricsAndLock: String,
    val about: String,
    val version: String,
    val searchSettings: String,
    val regionalLocaleOptions: String,
    val appLanguage: String,
    val selectLanguageDesc: String,
    val currencySymbol: String,
    val defineCurrencyDesc: String,
    val appCustomization: String,
    val reorderNavTabs: String,
    val manageNavTabsDesc: String,
    val themeColorSettings: String,
    val themeFlavorTitle: String,
    val themeFlavorDesc: String,
    val darkThemeTitle: String,
    val darkThemeDesc: String,
    val totalSavings: String,
    val totalRemittance: String,
    val totalEarnings: String,
    val payPeriod: String,
    val allocations: String,
    val addSalary: String,
    val editSalary: String,
    val newWorkout: String,
    val editWorkout: String,
    val workoutName: String,
    val sets: String,
    val reps: String,
    val instructions: String,
    val scheduleDay: String,
    val save: String,
    val cancel: String,
    
    // Salary Screen
    val totalCumulativeEarnings: String,
    val thisMonth: String,
    val nextPayday: String,
    val daysLeft: String,
    val incomeVsSavingsTrend: String,
    val income: String,
    val salaryAllocationPlayground: String,
    val allocationDesc: String,
    val projectedAnnualSavings: String,
    val estDisposableIncome: String,
    val history: String,
    val seeAll: String,
    val allTime: String,
    val thisYear: String,
    val highSavings: String,
    
    // Exercise Screen
    val scheduleWorkouts: String,
    val workouts: String,
    val setsDone: String,
    val active: String,
    val noWorkoutsLogged: String,
    
    // Settings Screen
    val dynamicColorSaturation: String,
    val fineTuneWallpaper: String,
    val dynamicColorTint: String,
    val extractAccentWallpaper: String,
    val themeControlsIntensity: String,
    val controlToneSaturation: String,
    val typographyLayoutSettings: String,
    val appFontFamily: String,
    val chooseGlobalTypeface: String,
    val backgroundStyle: String,
    val chooseBackgroundStyle: String,
    val navbarAnimation: String,
    val selectNavbarAnimation: String,
    val privacyAppLock: String,
    val privacyModeProtection: String,
    val maskSensitiveTotals: String,
    val biometricLockGuard: String,
    val protectAccountBiometrics: String,
    val dataManagement: String,
    val backupDatabase: String,
    val exportLocalDbCopy: String,
    val restoreDatabase: String,
    val importBackupDbFile: String,
    val exportFinancialHistory: String,
    val downloadCsvHistory: String
)

val EnglishStrings = AppStrings(
    salary = "Salary",
    exercise = "Exercise",
    settings = "Settings",
    visuals = "Visuals",
    themesAndStyles = "Themes & Styles",
    preferences = "Preferences",
    currencyAndMode = "Currency & Mode",
    security = "Security",
    biometricsAndLock = "Biometrics & Lock",
    about = "About",
    version = "KakeiboX v1.0",
    searchSettings = "Search settings...",
    regionalLocaleOptions = "Regional & Locale Options",
    appLanguage = "App Language",
    selectLanguageDesc = "Select localized app string translation language.",
    currencySymbol = "Currency Symbol",
    defineCurrencyDesc = "Define standard monetary symbol applied to entries.",
    appCustomization = "App Customization",
    reorderNavTabs = "Reorder Navigation Tabs",
    manageNavTabsDesc = "Manage and drag routes inside bottom layout navbar.",
    themeColorSettings = "Theme & Color Settings",
    themeFlavorTitle = "Theme Aesthetic Flavor",
    themeFlavorDesc = "Choose curated M3 Expressive design color palette.",
    darkThemeTitle = "App Dark Theme",
    darkThemeDesc = "Light, dark, or system-adaptive dark mode preference.",
    totalSavings = "Total Savings",
    totalRemittance = "Total Remittance",
    totalEarnings = "TOTAL EARNINGS",
    payPeriod = "PAY PERIOD",
    allocations = "ALLOCATIONS",
    addSalary = "Add Salary",
    editSalary = "Edit Salary",
    newWorkout = "New Workout",
    editWorkout = "Edit Workout",
    workoutName = "Workout Name",
    sets = "SETS",
    reps = "REPS",
    instructions = "Instructions / Notes",
    scheduleDay = "SCHEDULE DAY",
    save = "Save",
    cancel = "Cancel",
    
    // Salary Screen
    totalCumulativeEarnings = "TOTAL CUMULATIVE EARNINGS",
    thisMonth = "THIS MONTH",
    nextPayday = "NEXT PAYDAY",
    daysLeft = "Days Left",
    incomeVsSavingsTrend = "INCOME VS. SAVINGS TREND",
    income = "Income",
    salaryAllocationPlayground = "SALARY ALLOCATION PLAYGROUND",
    allocationDesc = "Adjust the slider to simulate target savings rates and project wealth trajectory.",
    projectedAnnualSavings = "PROJECTED ANNUAL SAVINGS",
    estDisposableIncome = "EST. DISPOSABLE INCOME",
    history = "History",
    seeAll = "See All",
    allTime = "All Time",
    thisYear = "This Year",
    highSavings = "High Savings",
    
    // Exercise Screen
    scheduleWorkouts = "SCHEDULE WORKOUTS",
    workouts = "Workouts",
    setsDone = "Sets Done",
    active = "Active",
    noWorkoutsLogged = "No workouts logged for",
    
    // Settings Screen
    dynamicColorSaturation = "Dynamic Color Saturation",
    fineTuneWallpaper = "Fine-tune wallpaper extraction intensity.",
    dynamicColorTint = "Dynamic Color Tint",
    extractAccentWallpaper = "Extract accent colors from device wallpaper (M3 mode only).",
    themeControlsIntensity = "Theme Controls Intensity",
    controlToneSaturation = "Control tone saturation and contrast (Neutral, Soft, Bright, Bold).",
    typographyLayoutSettings = "Typography & Layout Settings",
    appFontFamily = "App Font Family",
    chooseGlobalTypeface = "Choose global typeface applied to all text components.",
    backgroundStyle = "Background Style",
    chooseBackgroundStyle = "Choose background style for screen canvas backdrop.",
    navbarAnimation = "Navbar Animation",
    selectNavbarAnimation = "Select animation style for the floating navigation bar.",
    privacyAppLock = "Privacy & App Lock",
    privacyModeProtection = "Privacy Mode Protection",
    maskSensitiveTotals = "Mask sensitive financial totals with dots on dashboard.",
    biometricLockGuard = "Biometric Lock Guard",
    protectAccountBiometrics = "Protect account information with fingerprint lock.",
    dataManagement = "Data Management",
    backupDatabase = "Backup Database",
    exportLocalDbCopy = "Export a copy of your local database (.db) file to device storage.",
    restoreDatabase = "Restore Database",
    importBackupDbFile = "Import a previously backed up (.db) file to restore your data.",
    exportFinancialHistory = "Export Financial History",
    downloadCsvHistory = "Download history records, wage totals, and travels as CSV file."
)

val JapaneseStrings = AppStrings(
    salary = "給与",
    exercise = "運動",
    settings = "設定",
    visuals = "ビジュアル",
    themesAndStyles = "テーマ＆スタイル",
    preferences = "環境設定",
    currencyAndMode = "通貨＆モード",
    security = "セキュリティ",
    biometricsAndLock = "生体認証＆ロック",
    about = "アプリ情報",
    version = "KakeiboX v1.0",
    searchSettings = "設定を検索...",
    regionalLocaleOptions = "地域・言語設定",
    appLanguage = "アプリ言語",
    selectLanguageDesc = "表示言語を選択します。",
    currencySymbol = "通貨記号",
    defineCurrencyDesc = "標準で使用する通貨記号を設定します。",
    appCustomization = "アプリのカスタマイズ",
    reorderNavTabs = "ナビゲーション順序",
    manageNavTabsDesc = "ボトムバーのタブ順序を変更します。",
    themeColorSettings = "テーマ＆カラー設定",
    themeFlavorTitle = "デザインテーマ",
    themeFlavorDesc = "お好みのカラーパレットを選択します。",
    darkThemeTitle = "ダークモード設定",
    darkThemeDesc = "ライト、ダーク、システム連動の切り替え。",
    totalSavings = "総貯蓄額",
    totalRemittance = "総送金額",
    totalEarnings = "総収入",
    payPeriod = "給与期間",
    allocations = "配分設定",
    addSalary = "給与を追加",
    editSalary = "給与を編集",
    newWorkout = "新規ワークアウト",
    editWorkout = "ワークアウト編集",
    workoutName = "種目名",
    sets = "セット数",
    reps = "回数",
    instructions = "メモ・説明",
    scheduleDay = "実施曜日",
    save = "保存",
    cancel = "キャンセル",
    
    // Salary Screen
    totalCumulativeEarnings = "累計総収入",
    thisMonth = "今月の給与",
    nextPayday = "次回の給料日",
    daysLeft = "日残り",
    incomeVsSavingsTrend = "収入・貯蓄推移",
    income = "収入",
    salaryAllocationPlayground = "給与配分シミュレーション",
    allocationDesc = "スライダーを調整して目標貯蓄率と資産の推移をシミュレーションします。",
    projectedAnnualSavings = "年間予想貯蓄額",
    estDisposableIncome = "推定可処分所得",
    history = "履歴",
    seeAll = "すべて表示",
    allTime = "全期間",
    thisYear = "今年",
    highSavings = "高貯蓄",
    
    // Exercise Screen
    scheduleWorkouts = "ワークアウト予定",
    workouts = "ワークアウト",
    setsDone = "セット完了",
    active = "有効",
    noWorkoutsLogged = "ワークアウトが登録されていません:",
    
    // Settings Screen
    dynamicColorSaturation = "ダイナミックカラー彩度",
    fineTuneWallpaper = "壁紙カラー抽出の強度を微調整します。",
    dynamicColorTint = "ダイナミックカラーティント",
    extractAccentWallpaper = "壁紙からアクセントカラーを抽出します。",
    themeControlsIntensity = "テーマコントラスト強度",
    controlToneSaturation = "トーンの彩度とコントラストを調整します。",
    typographyLayoutSettings = "フォント＆レイアウト設定",
    appFontFamily = "アプリフォント",
    chooseGlobalTypeface = "すべてのテキストに使用するフォントを選択します。",
    backgroundStyle = "背景スタイル",
    chooseBackgroundStyle = "画面背景のスタイルを選択します。",
    navbarAnimation = "ナビバーアニメーション",
    selectNavbarAnimation = "ナビゲーションバーのアニメーションを選択します。",
    privacyAppLock = "プライバシー＆アプリロック",
    privacyModeProtection = "プライバシーモード保護",
    maskSensitiveTotals = "ダッシュボードの金額をドットで非表示にします。",
    biometricLockGuard = "生体認証ロック",
    protectAccountBiometrics = "指紋認証でアカウント情報を保護します。",
    dataManagement = "データ管理",
    backupDatabase = "データベースバックアップ",
    exportLocalDbCopy = "ローカルデータベースのバックアップを出力します。",
    restoreDatabase = "データベース復元",
    importBackupDbFile = "バックアップファイルからデータを復元します。",
    exportFinancialHistory = "履歴データCSV出力",
    downloadCsvHistory = "給与・支出履歴をCSVファイルとして保存します。"
)

fun getAppStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.JAPANESE -> JapaneseStrings
    }
}
